# Generated by Django 4.1.3 on 2023-05-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='likes',
        ),
    ]
