# Generated by Django 4.1.3 on 2023-05-27 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_remove_postlikes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikes', to='community_app.posts'),
        ),
    ]
