# Generated by Django 4.1.3 on 2023-05-27 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_alter_postlikes_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.posts'),
        ),
    ]
