# Generated by Django 4.1.3 on 2023-05-27 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_assethistory_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_app', '0004_alter_postlikes_post_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
