# Generated by Django 4.1.3 on 2023-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0004_commentlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
