# Generated by Django 4.1.3 on 2023-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0005_alter_postcomments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
