# Generated by Django 4.1.3 on 2023-05-27 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_app', '0005_rename_posts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='Like',
        ),
    ]
