# Generated by Django 4.1.3 on 2023-05-27 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_app', '0006_rename_postlikes_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='Comment',
        ),
    ]
