# Generated by Django 4.1.3 on 2023-05-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0007_rename_postcomments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='asset',
        ),
    ]
