# Generated by Django 4.1.3 on 2023-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0007_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
