# Generated by Django 4.1.3 on 2023-05-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0008_remove_post_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtags',
            new_name='tags',
        ),
    ]
