# Generated by Django 4.1.3 on 2023-05-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0009_rename_hashtags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
