# Generated by Django 4.1.3 on 2023-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0018_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy_settings',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
