services:
    web:
        image: "${WEB_IMAGE}"
        #command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/mediafiles
        ports:
            - 8000:8000
        env_file: .env
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine
        command: redis-server
        expose:
            - 6379

volumes:
    static_volume:
    media_volume:
