services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
            cache_from:
                - "${WEB_IMAGE}"
        image: "${WEB_IMAGE}"
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/mediafiles
        expose:
            - 8000
        env_file: .env

volumes:
    static_volume:
    media_volume:
