services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file: .env
  redis:
    image: redis:latest

volumes:
  static_volume:
  media_volume:
