services:
  web:
    build: ./app
    command: python manage.py migrate
    command: python manage.py makemigrations
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
