# Generated by Django 4.1.3 on 2023-05-23 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings_app', '0002_remove_settings_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='EUR', max_length=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='dateTimeFormat',
            field=models.CharField(default='DD.MM.YYYY HH:mm', max_length=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='dark', max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
