# Generated by Django 4.2 on 2023-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_settings_currency_settings_datetimeformat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='assetAmountChanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='changedIpAdress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='commentedMessage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='followMessage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='likedCommentMessage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='likedPostMessage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='sharedPostMessage',
            field=models.BooleanField(default=False),
        ),
    ]
