# Generated by Django 4.1.3 on 2023-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_remove_settings_changedipadress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='assetAmountChanged',
            field=models.BooleanField(default='None'),
        ),
    ]
