# Generated by Django 4.1.3 on 2023-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_alter_settings_assetamountchanged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='assetAmountChanged',
            new_name='hasAssetAmountChanged',
        ),
        migrations.AddField(
            model_name='settings',
            name='hasLikedComment',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='hasLikedPost',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='hasNewComment',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='hasNewFollower',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='hasSharedPost',
            field=models.BooleanField(default=None),
        ),
    ]
