# Generated by Django 4.1.3 on 2023-05-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_rename_assetamountchanged_settings_hasassetamountchanged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='hasLikedComment',
        ),
    ]
