# Generated by Django 4.1.3 on 2023-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_remove_settings_haslikedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hasLikedComment',
            field=models.BooleanField(default=None),
        ),
    ]
