# Generated by Django 4.1.3 on 2023-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0010_settings_haslikedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='hasAssetAmountChanged',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasLikedComment',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasLikedPost',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasNewComment',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasNewFollower',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasSharedPost',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
