# Generated by Django 4.1.3 on 2023-05-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_alter_settings_hasassetamountchanged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='hasAssetAmountChanged',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasLikedComment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasLikedPost',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasNewComment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasNewFollower',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hasSharedPost',
            field=models.BooleanField(default=True),
        ),
    ]
