# Generated by Django 4.1.3 on 2023-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0012_alter_settings_hasassetamountchanged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='posts_privacy_settings',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
