# Generated by Django 4.1.3 on 2023-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0013_settings_posts_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='watchlist_privacy_settings',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
