# Generated by Django 4.1.3 on 2023-07-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0014_settings_watchlist_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dashboard_privacy_settings',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
