# Generated by Django 4.1.3 on 2023-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0015_settings_dashboard_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(default='de', max_length=30),
        ),
    ]
