# Generated by Django 4.1.3 on 2023-05-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='follower_user',
        ),
    ]
