# Generated by Django 4.1.3 on 2023-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_user_userfollowing_follower_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/default_profile.png', upload_to='profile_pics'),
        ),
    ]
