# Generated by Django 4.1.3 on 2023-06-06 13:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='static/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
