# Generated by Django 4.1.3 on 2023-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_pics'),
        ),
    ]
