# Generated by Django 4.1.3 on 2023-07-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_userprofileinfo_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
