# Generated by Django 4.1.3 on 2023-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_userprofileinfo_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ws_state',
            field=models.BooleanField(default=False),
        ),
    ]
