# Generated by Django 4.1.3 on 2023-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_remove_customuser_ws_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ws_state',
            field=models.BooleanField(default=False),
        ),
    ]
