# Generated by Django 4.1.3 on 2023-07-19 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_customuser_ws_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_banner', models.CharField(choices=[('/static/banner_1.png', 'Banner 1'), ('/static/banner_2.png', 'Banner 2')], default='/static/banner_1.png', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
