# Generated by Django 4.1.3 on 2023-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_userprofileinfo_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebanner',
            name='profile_banner',
            field=models.CharField(choices=[('/static/banner_1.png', 'Banner 1'), ('/static/banner_2.png', 'Banner 2'), ('/static/banner_3.png', 'Banner 3'), ('/static/banner_4.png', 'Banner 4')], default='/static/banner_1.png', max_length=255),
        ),
    ]
