# Generated by Django 4.1.3 on 2023-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_userprofileinfo_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
