# Generated by Django 4.1.3 on 2023-07-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_alter_customuser_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='channel_name',
        ),
    ]
