# Generated by Django 4.1.3 on 2023-07-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_remove_customuser_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
