# Generated by Django 4.1.3 on 2023-07-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_profilebanner_profile_banner'),
        ('user_app', '0019_customuser_channel_name'),
    ]

    operations = [
    ]
