# Generated by Django 4.1.3 on 2023-07-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_merge_20230725_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='channel_name',
            new_name='channel_layer',
        ),
    ]
