# Generated by Django 4.1.3 on 2023-05-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assethistory",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
