# Generated by Django 4.1.3 on 2023-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_assethistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethistory',
            name='value',
            field=models.FloatField(max_length=30),
        ),
    ]
