# Generated by Django 4.1.3 on 2023-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_assethistory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
