# Generated by Django 4.1.3 on 2023-05-29 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0006_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxparticipants',
            name='last_message',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboxparticipants',
            name='last_message_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
