# Generated by Django 4.1.3 on 2023-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0007_inboxparticipants_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxparticipants',
            name='last_message_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
