# Generated by Django 4.1.3 on 2023-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0008_alter_inboxparticipants_last_message_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxparticipants',
            name='last_message',
            field=models.CharField(max_length=30),
        ),
    ]
