# Generated by Django 4.1.3 on 2023-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0009_alter_inboxparticipants_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
