<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-05-04 16:10
=======
# Generated by Django 4.1.3 on 2023-05-06 09:15
>>>>>>> main

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('api_app', '0003_alter_assethistory_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0002_alter_assethistory_date'),
>>>>>>> main
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.DateField()),
                ('purchaseValue', models.CharField(max_length=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
