# Generated by Django 4.1.3 on 2023-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_remove_portfolio_purchasevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
