# Generated by Django 4.1.3 on 2023-05-23 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_assethistory_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0003_portfolio_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Transaction',
        ),
    ]
