# Generated by Django 4.2 on 2023-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_rename_portfolio_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
