# Generated by Django 4.1.3 on 2023-06-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='addet_at',
            new_name='added_at',
        ),
    ]
