# Generated by Django 4.1.3 on 2023-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_rename_addet_at_watchlist_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='price_change',
            field=models.IntegerField(default=30),
        ),
    ]
