# Generated by Django 4.1.3 on 2023-07-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_asset_imageurl'),
        ('dashboard_app', '0010_watchlistlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='price_change',
        ),
        migrations.CreateModel(
            name='WatchlistAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('price_change', models.IntegerField(default=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.asset')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.watchlist')),
            ],
        ),
    ]
