# Generated by Django 4.1.3 on 2023-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_remove_watchlist_added_at_remove_watchlist_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='privacy_settings',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
