# Generated by Django 4.1.3 on 2023-07-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_watchlist_privacy_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistLike',
        ),
    ]
