name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        django-version: [4.1.3]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "Django~=${{ matrix.django-version }}.0"
    - name: Setup Tests
      run: |
        echo "$(python --version) / Django $(django-admin --version)"
        cd app
    - name: Community App Tests
      run: |
        cd app
        python manage.py test community_app
    - name: Dashboard App Tests
      run: |
        cd app
        python manage.py test dashboard_app
    - name: Messaging App Tests
      run: |
        cd app
        python manage.py test messaging_app
    #- name: Notification App Tests
    #  run: |
    #    cd app
    #    python manage.py test notification_app
    - name: Settings App Tests
      run: |
        cd app
        python manage.py test settings_app
    #- name: User App Tests
    #  run: |
    #    cd app
    #    python manage.py test user_app
