name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        django-version: [3.2, 4.0, 4.1, 4.1.3]
        exclude:
          # Python 3.6 is not compatible with 4.0
          - python-version: "3.6"
            django-version: "4.0"
          # Python 3.6 is not compatible with 4.1
          - python-version: "3.6"
            django-version: "4.1"
          # Python 3.7 is not compatible with 4.0
          - python-version: "3.7"
            django-version: "4.0"
          # Python 3.7 is not compatible with 4.1
          - python-version: "3.7"
            django-version: "4.1"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
